### ISSUE TITLE
Does this code connect with external wss APIs?

### ISSUE THREAD

**Issue by slidenerd** [blgo/flask-realtime-restapi#18]
I am sorry if this is a newbie question. I see that you have defined several charts events in your socketio code and you are using Flask Socket IO. I am trying to connect to several exchanges such as GDAX etc to receive BTC data from their websocket streams, can this same library flask socket IO be used to achieve this or is flask socket IO only a server side component of socketio?

**Comment by blgo** [comment]
Flask Socket IO is a Websocket server only, does not include a WS client, but you could choose your own and add it somewhere in the code.
